from django.urls import path
from .views import *

urlpatterns = [
    path('', LandingView.as_view(), name='landing'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('password-change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('home/', HomeView.as_view(), name='home'),
    path('help-request/', HelpRequestCreateView.as_view(), name='help_request'),
    path('chat/', ChatListView.as_view(), name='chat'),
    path('courses/', CourseListView.as_view(), name='courses'),
    path('forum/', ForumListView.as_view(), name='forum_list'),
    path('forum/create/', ForumCreateView.as_view(), name='forum_create'),
    path('donate/', DonationCreateView.as_view(), name='donate'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('history/', HistoryView.as_view(), name='history'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('regions/', RegionListView.as_view(), name='region_list'),
    path('works/', WorkListView.as_view(), name='work_list'),
    path("work_create/", work_create_view, name="work_create"),
    path("work_detail/<int:pk>/", work_detail_view, name="work_detail"),
    path("application_create/<int:pk>/", application_create_view, name="application_create"),
    path("application_list/", application_list_view, name="application_list"),
    path("application_detail/<int:pk>/", application_detail_view, name="application_detail"),
    path("application_update/<int:pk>/", application_update_view, name="application_update"),
    path("application_delete/<int:pk>/", application_delete_view, name="application_delete"),
    path("work_update/<int:pk>/", work_update_view, name="work_update"),
    path("work_delete/<int:pk>/", work_delete_view, name="work_delete"),
    path('my-applications/', my_applications_view, name='my_applications'),
    path('application/<int:pk>/accept/', accept_application, name='accept_application'),
    path('notifications/', get_notifications, name='get_notifications'),
    path('notifications/<int:notification_id>/mark-read/', mark_notification_read, name='mark_notification_read'),
]
