# Generated by Django 4.2.17 on 2025-01-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat_type',
            field=models.CharField(choices=[('legal', 'Правовая поддержка'), ('psychological', 'Психологическая поддержка'), ('general', 'Общая поддержка')], default='general', max_length=20),
        ),
    ]
